import type { Metadata } from 'next';
import { LegalShell } from '@/components/layout/LegalShell';
import { ManageCookiesButton } from '@/components/layout/CookieConsent';
import { isLocale, defaultLocale, type Locale } from '@/dictionaries';

export async function generateMetadata({ params }: { params: { lang: string } }): Promise<Metadata> {
  const lang: Locale = isLocale(params.lang) ? params.lang : defaultLocale;
  return {
    title: lang === 'en' ? 'Privacy policy' : 'Politique de confidentialité',
    description:
      lang === 'en'
        ? 'Herakia privacy policy — processing of personal data, purposes, retention period and GDPR rights.'
        : 'Politique de confidentialité d’Herakia — traitement des données personnelles, finalités, durée de conservation et droits RGPD.',
    alternates: {
      canonical: `/${lang}/confidentialite`,
      languages: { fr: '/fr/confidentialite', en: '/en/confidentialite' },
    },
    robots: { index: false, follow: true },
  };
}

export default function ConfidentialitePage({ params }: { params: { lang: string } }) {
  const lang: Locale = isLocale(params.lang) ? params.lang : defaultLocale;

  if (lang === 'en') {
    return (
      <LegalShell title="Privacy policy" lastUpdated="8 October 2026" updatedLabel="Last updated">
        <p>
          Herakia places particular importance on protecting your personal data. This policy describes
          what data we collect, why, how long we keep it and what your rights are, in accordance with
          the General Data Protection Regulation (GDPR).
        </p>

        <h2>Data controller</h2>
        <p>
          The data controller is HERAKIA, a French SAS with a share capital of €40,000, whose registered
          office is at 156 boulevard Raymond Poincaré, 06160 Antibes, France (130 678 162 R.C.S.
          Antibes), reachable at{' '}
          <a href="mailto:contact@herakia.com">contact@herakia.com</a>.
        </p>

        <h2>Data collected</h2>
        <ul>
          <li>
            Via the contact form: name, email, phone number, company, type of need and message.
          </li>
          <li>
            Via a voice conversation with Tia, our AI assistant: the conversation is recorded and
            transcribed, together with its date, its duration and an automatic summary.
          </li>
          <li>
            Via browsing, only if you accept it: audience data collected by Google Analytics (pages
            viewed, traffic source, device type, approximate location).
          </li>
        </ul>

        <h2>Purposes &amp; legal basis</h2>
        <ul>
          <li>Responding to your requests and contacting you back — legal basis: pre-contractual measures / legitimate interest.</li>
          <li>
            Handling voice conversations with Tia and improving the assistant — legal basis:
            pre-contractual measures / legitimate interest.
          </li>
          <li>Measuring the site’s audience — legal basis: your consent.</li>
        </ul>

        <h2>Recipients</h2>
        <p>
          Your data is intended for Herakia and is not resold. It may pass through our technical
          subprocessors:
        </p>
        <ul>
          <li>Vercel Inc. — website hosting;</li>
          <li>Supabase — database, hosted in the European Union;</li>
          <li>Resend — sending the emails generated by the contact form;</li>
          <li>ElevenLabs — voice conversations with Tia;</li>
          <li>Google (Google Analytics) — audience measurement, subject to your consent.</li>
        </ul>
        <p>
          Some of these providers are established in the United States. These transfers are governed
          by the EU–US Data Privacy Framework or by the European Commission’s standard contractual
          clauses.
        </p>

        <h2>Retention period</h2>
        <p>
          Data from the contact form and from conversations with Tia is kept for 3 years from the last
          contact, then deleted or anonymised. Audience-measurement cookies are kept for a maximum of
          13 months.
        </p>

        <h2>Your rights</h2>
        <p>
          You have a right of access, rectification, erasure, restriction, objection and portability of
          your data. To exercise them, write to{' '}
          <a href="mailto:contact@herakia.com">contact@herakia.com</a>. You may also lodge
          a complaint with the CNIL (
          <a href="https://www.cnil.fr" target="_blank" rel="noopener noreferrer">cnil.fr</a>).
        </p>

        <h2>Cookies</h2>
        <p>
          The site only sets audience-measurement cookies (Google Analytics), and only once you have
          accepted them in the banner shown on your first visit. If you decline, no measurement cookie
          is set and the site works in exactly the same way. Your choice is stored in your browser for 6
          months, after which it is asked again; no advertising cookie is used.
        </p>
        <p>
          You can change your mind at any time: <ManageCookiesButton />.
        </p>
      </LegalShell>
    );
  }

  return (
    <LegalShell title="Politique de confidentialité" lastUpdated="8 octobre 2026">
      <p>
        Herakia accorde une importance particulière à la protection de vos données personnelles.
        Cette politique décrit quelles données nous collectons, pourquoi, combien de temps nous les
        conservons et quels sont vos droits, conformément au Règlement Général sur la Protection des
        Données (RGPD).
      </p>

      <h2>Responsable du traitement</h2>
      <p>
        Le responsable du traitement est HERAKIA, SAS au capital de 40&nbsp;000&nbsp;€, dont le siège
        social est situé 156 boulevard Raymond Poincaré, 06160 Antibes (130&nbsp;678&nbsp;162 R.C.S.
        Antibes), joignable à l’adresse{' '}
        <a href="mailto:contact@herakia.com">contact@herakia.com</a>.
      </p>

      <h2>Données collectées</h2>
      <ul>
        <li>
          Via le formulaire de contact&nbsp;: nom, email, numéro de téléphone, entreprise, type de
          besoin et message.
        </li>
        <li>
          Via une conversation vocale avec Tia, notre assistante IA&nbsp;: la conversation est
          enregistrée et transcrite, avec sa date, sa durée et un résumé automatique.
        </li>
        <li>
          Via la navigation, uniquement si vous l’acceptez&nbsp;: données d’audience collectées par
          Google Analytics (pages consultées, provenance, type d’appareil, localisation approximative).
        </li>
      </ul>

      <h2>Finalités &amp; base légale</h2>
      <ul>
        <li>
          Répondre à vos demandes et vous recontacter — base légale&nbsp;: mesures précontractuelles
          / intérêt légitime.
        </li>
        <li>
          Traiter les conversations vocales avec Tia et améliorer l’assistante — base légale&nbsp;:
          mesures précontractuelles / intérêt légitime.
        </li>
        <li>Mesurer l’audience du site — base légale&nbsp;: votre consentement.</li>
      </ul>

      <h2>Destinataires</h2>
      <p>
        Vos données sont destinées à Herakia et ne sont pas revendues. Elles peuvent transiter par nos
        sous-traitants techniques&nbsp;:
      </p>
      <ul>
        <li>Vercel Inc. — hébergement du site&nbsp;;</li>
        <li>Supabase — base de données, hébergée dans l’Union européenne&nbsp;;</li>
        <li>Resend — envoi des emails issus du formulaire de contact&nbsp;;</li>
        <li>ElevenLabs — conversations vocales avec Tia&nbsp;;</li>
        <li>Google (Google Analytics) — mesure d’audience, sous réserve de votre consentement.</li>
      </ul>
      <p>
        Certains de ces prestataires sont établis aux États-Unis. Ces transferts sont encadrés par le
        Data Privacy Framework UE–États-Unis ou par les clauses contractuelles types de la Commission
        européenne.
      </p>

      <h2>Durée de conservation</h2>
      <p>
        Les données issues du formulaire de contact et des conversations avec Tia sont conservées
        pendant 3 ans à compter du dernier contact, puis supprimées ou anonymisées. Les cookies de
        mesure d’audience sont conservés 13 mois au maximum.
      </p>

      <h2>Vos droits</h2>
      <p>
        Vous disposez d’un droit d’accès, de rectification, d’effacement, de limitation, d’opposition
        et de portabilité de vos données. Pour les exercer, écrivez à{' '}
        <a href="mailto:contact@herakia.com">contact@herakia.com</a>. Vous pouvez également introduire une
        réclamation auprès de la CNIL (
        <a href="https://www.cnil.fr" target="_blank" rel="noopener noreferrer">
          cnil.fr
        </a>
        ).
      </p>

      <h2>Cookies</h2>
      <p>
        Le site ne dépose que des cookies de mesure d’audience (Google Analytics), et seulement après
        que vous les avez acceptés dans le bandeau affiché à votre première visite. Si vous refusez,
        aucun cookie de mesure n’est déposé et le site fonctionne exactement de la même façon. Votre
        choix est mémorisé dans votre navigateur pendant 6 mois, puis redemandé&nbsp;; aucun cookie
        publicitaire n’est utilisé.
      </p>
      <p>
        Vous pouvez changer d’avis à tout moment&nbsp;: <ManageCookiesButton />.
      </p>
    </LegalShell>
  );
}
